### ISSUE TITLE
Add the length and precision  of a column in column definition

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#151]
This is a feature request.  I just noticed that OGR does provide the length and precision of fields.

For example ogrinfo gives me something like this when quering a SQL Server db

`
MembersID: Integer (10.0)
Local: String (12.0)
UGroup: String (4.0)
FirstName: String (25.0)
LastName: String (25.0)
MiddleInit: String (1.0)
Suffix: String (3.0)
MaritalStatus: String (1.0)
Street1: String (35.0)
Street2: String (25.0)
City: String (27.0)
State: String (2.0)
Zip: String (10.0)
ZipPlus4: String (4.0)
BirthDate: DateTime (16.0)

`

But when it comes thru on the Postgres side, this extra info is lost, so all I get is an undefined length 

`City varchar`

instead of 

`City varchar(27)`

I suppose some people like those PostgreSQL nuts who think all varchar should be text (undefined length) might prefer the current behavior, so perhaps make it an option (turned on by default :) )

**Comment by pramsey** [comment]
Hm. I guess so. All the typmods do is restrict what can go in, there's no internal storage difference between something stored as `varchar` and `varchar(10)`

**Comment by robe2** [comment]
Yah main reason for me why it would be nice is I do a lot of

`CREATE TABLE  local_tbl AS 
SELECT *
FROM foreign_table
WHERE only_the_data_i_want;`

So saves time not having to go thru the trouble of adding back those lengths.

**Comment by pramsey** [comment]
There will be a pretty strong dependence on whether the source driver actually passes that info into OGR in the first place, so that the FDW can read it back from OGR http://www.gdal.org/ogr__api_8h.html#aa6500186e3f22761a615428c55bba0ce

**Comment by robe2** [comment]
True, like the shapefile/dbase one doesn't, though it really could with some work on GDAL side.
Some their won' t be any hope for like csv, xlsx and so forth,

but a lot do like I think most relational you would get under the ODBC driver would have it so that's still a fair number.

Want me to take a stab at providing a patch?  

It will do what it does now for drivers that don't provide the extra info

Will have another config option to enable it (you decide if its default or not, might be better to make it not default for backward compatibility).

**Comment by pramsey** [comment]
Sure, if you want some patch fun, you can do it. Otherwise I'm fine to take a stab. Looks like a relatively small patch on `ogrTypeToPgType`. My only concern is that the way drivers use that info might be variable. The documentation on [OGR_Fld_GetWidth](http://www.gdal.org/ogr__api_8h.html#aa6500186e3f22761a615428c55bba0ce) says "Get the formatting width for this field". Which means...? Similarly the precision function talks about the "formatting precision". The documentation is not necessarily talking about typmod or data-level metadata, it's definitely display-level. Width and precision in OGR world seem more similar to the "justification" they live near, rather than to typmod.

**Comment by robe2** [comment]
We could limit it just to strings.  It's more an issue with varchar than anything else.
