### ISSUE TITLE
Make the "ogr_fdw_info" program a pgsql function in the OGR_FDW extension

### ISSUE THREAD

**Issue by bvthomsen** [pramsey/pgsql-ogr-fdw#19]
It it possible to convert the utility program ogd_fdw_info into a PL/pgSQL function residing in the OGR_FDW extension ? And let this function create the fdw table directly ?

Something  like:
SQL> CREATE EXTENSION OGR_FDW;

SQL> SELECT OGR_FDW_CREATE_TABLE(' ... OGR-def....', 'layername', 'my_new_table');
or 
SQL> SELECT OGR_FDW_CREATE_TABLE('...OGR-def....','layername','my_new_table',MultiPolygon,4326);

The last call would create the table with a predefined typemod on the geometry column.

**Comment by pramsey** [comment]
It's possible. Also in 9.5 there will be an way to pull in an FDW table definition directly from a server as a standard syntax. I'm tempted to wait for the standard way.

**Comment by robe2** [comment]
This is a bit of a hack I use which you might find useful.  I created this mostly so I don't have to hunt around for the ogr_fdw_info executable.  I generally have to tweak the output anyway so don't bother with making it automatically generate the tables:

```
CREATE OR REPLACE FUNCTION generate_sql_table(data_source text, layer text) RETURNS TEXT AS
$$
DECLARE str_command text;
BEGIN
        DROP TABLE IF EXISTS ogr_fdw_out;
        CREATE TEMP TABLE ogr_fdw_out(out text);
        EXECUTE 'COPY ogr_fdw_out FROM PROGRAM ''"C:/Program Files/PostgreSQL/9.4/bin/ogr_fdw_info" -s "' || data_source || '" -l "' || layer || '"'' ';
        RETURN (SELECT string_agg(out,E'\n') from ogr_fdw_out);
END;

$$
language 'plpgsql' SECURITY DEFINER;
```
Then to use, I do something like this:

```
SELECT generate_sql_table('c:/fdw_data/gisdata/nps_boundary.kml', 'National Park Boundaries') ;

```

**Comment by bvthomsen** [comment]
Thanks Regina,  for the tip regarding the "COPY .. FROM PROGRAM". That is a pretty awesome function in Postgres. 

Where does the external program run (client or server) and in which security context ? It could be a security nightmare if it's run under a privileged user account on the server. The Postgres documentation is a little bit unclear (or maybe I'm simply obtuse this saturday) 

Regarding the manual tweaking: Yes, It would be nice if  the ogr_fdw_info program could produce the correct geometry modifiers and SRID directly in the "CREATE TABLE" statement. 

And a great many thanks to you, Poul, for creating this great datawrapper.

**Comment by robe2** [comment]
External program runs on the server.  

COPY PROGRAM can only be used by super users because it runs under the context of the postgres account.   That's why when I create the function, I mark it as security definer if I want regular users to be able to use it.

There is a psql equivalent called  \copy from program which runs client side to achieve the same, except would launch an executable on client's computer and pipe into table in the database.  

As a side note about the type modifier.  It's not sufficient to just mark it as say geometry(MULTIPOLYGON, 4326) or at least I wasn't successful doing that.  Underlying the FDW still returns ST_SRID = 0 so intersects and other junk would fail.  That's why when I need it that way, I wrap the table in a view and cast the geometry to something like  ST_SetSRID(geom,4326)::geometry(MULTIPOLYGON, 4326)

**Comment by pramsey** [comment]
I'm going to close this out, but perhaps you could transfer the wisdom to a wiki page? Rather than adding this kind of hack I'd rather just promote the use of IMPORT in 9.5+.

**Comment by bvthomsen** [comment]
OK for me..
Regards Bo Victor
Den 21/01/2016 23.23 skrev "Paul Ramsey" <notifications@github.com>:

**Comment by robe2** [comment]
For those interested I already have an article written and have updated the function to better handle strange cases in file names etc.

Article is here. Feel free to link somewhere.

http://www.postgresonline.com/journal/archives/345-Import-Foreign-Schema-hack-with-OGR_FDW-and-reading-LibreOffice-calc-workbooks.html
