### ISSUE TITLE
Applying to Windows

### ISSUE THREAD

**Issue by mtravis** [pramsey/pgsql-ogr-fdw#5]
Is it possible to use this in Windows?

**Comment by robe2** [comment]
It took me a while to figure out how to hack the the gdal configure script to so that it uses native ODBC windows support, but finally got it.  I'm rebuilding binaries and will post soon and also the 9.3s

So far I can query my SQL Server 2008 R2 sitting on another server from my PostgreSQL server and generate the structure with something like.  Need to fully qualify the schema.

```
ogr_fdw_info -s ODBC:"sqlserveruser/sqlserverpassword@SQLSystemDSNName" -l dbo.Orders

```


Paul -- sadly it thinks all sql server tables are spatial.  I think this is an issue with the GDAL driver since GDAL ogrinfo -so reports Geometry (any) unknown.  Oh well.  There is also an issue with the datetime format.  I'm not sure if that is a gdal issue or the ogr_fdw, but I had to change all the things it reported as timestamp to varchar.

Anyway great progress, and hasn't crashed on me yet (so seems more robust than the odbc_fdw).  This will be really useful for pulling data from SQL Server for clients that have legacy SQL Servers they can't decommission yet.

**Comment by mtravis** [comment]
Thank you for this. I will be testing it out when I get back to work next
week.

**Comment by robe2** [comment]
I've updated the 9.4 binaries and will be posting the 9.3 later today or tomorrow.

http://www.postgresonline.com/journal/archives/340-Foreign-Data-Wrappers-for-PostgreSQL-9.4-Windows.html (I do have the 9.3 64-bit as well just not linked yet until I have the 9.3 32-bit) -- just replace 94 with 93 in links.

  I'm so excited I did my first cross update between SQL Server and PostgreSQL (from PostgreSQL). 


It was a little slow (3 seconds), but good enough for my needs.  I'll be posting some ODBC examples later after I've tested with MS Access.

Paul -- you made my new year already.  I'll try not to bug you for the rest of the year :)
